version: 2.1

orbs:
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0

jobs:
  deploy:
    docker:
      - image: cimg/openjdk:17.0.9
    steps:
      - setup_remote_docker
      - checkout
      - heroku/install
      - run:
          name: Heroku Container Push
          command: |
              heroku container:login
              heroku container:push web --app chinhow-su-devops --arg jdbc_database_url=$JDBC_DATABASE_URL,jdbc_database_username=$JDBC_DATABASE_USERNAME,jdbc_database_password=$JDBC_DATABASE_PASSWORD 
              heroku container:release web -a chinhow-su-devops

workflows:
  simple_workflow:
    jobs:
      - deploy